sudo: required
services:
  - docker

before_install:
  - docker build -t sriharikancharla/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sriharikancharla/react-test npm test -- --coverage

after_success:
  - docker build -t sriharikancharla/multi-client ./client
  - docker build -t sriharikancharla/multi-nginx ./nginx
  - docker build -t sriharikancharla/multi-server ./server
  - docker build -t sriharikancharla/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push sriharikancharla/multi-client
  - docker push sriharikancharla/multi-nging
  - docker push sriharikancharla/multi-server
  - docker push sriharikancharla/multi-worker